# Generated by Django 5.2 on 2025-04-22 11:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_userregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('registration', 'User Registration'), ('login', 'User Login'), ('export', 'Data Export'), ('upload', 'File Upload'), ('delete', 'Delete Action'), ('view', 'View Action'), ('other', 'Other Action')], max_length=20)),
                ('description', models.TextField()),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
